{% set name = "libfaketime" %}
{% set version = "0.9.9" %}
{% set sha256 = "57d0181150361c0a9b5c8eef05b11392f6134ada2c2d998e92e63daed639647c" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wolfcw/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - test_makefile.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make

test:
  commands:
    - faketime --help

about:
  home: https://github.com/wolfcw/libfaketime
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: libfaketime intercepts various system calls that programs use to retrieve the current date and time.

  description: |
    libfaketime intercepts various system calls that programs use to retrieve the
    current date and time. It then reports modified (faked) dates and times (as
    specified by you, the user) to these programs. This means you can modify the
    system time a program sees without having to change the time system-wide.

extra:
  recipe-maintainers:
    - pvanheus
